from .goose import Goose
from .alligator import Alligator
from .alpaca import Alpaca
from .bird import Bird
from .donkey import Donkey
from .duck import Duck
from .fish import Fish
from .frog import Frog
from .goat import Goat
from .lizard import Lizard
from .llama import Llama
from .pig import Pig
from .snake import Snake
from .toad import Toad
from .tortoise import Tortoise
from .turtle import Turtle